<a href="https://colab.research.google.com/github/Ilyabuchnev/project/blob/DZ-1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Библиотека numpy ДЗ1

Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [ ]:
import numpy as np
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a



array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
a.shape

(5, 2)

In [ ]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [ ]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [ ]:
a_centered.shape

(5, 2)

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
f = a_centered[0:,:1].copy()  
f                     

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [ ]:
e = a_centered[0:,1: ].copy()
e

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [ ]:
f.shape

(5, 1)

In [ ]:
e.shape
 

(5, 1)

## a_centered_sp = np.dot(e,f) - у меня не получилось использовать эту формулу, не знаю почему, вот такая ошибка:ValueError                                Traceback (most recent call last)
<ipython-input-59-45676b003191> in <module>()
----> 1 sp = np.dot(e,f)

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: shapes (5,1) and (5,1) not aligned: 1 (dim 1) != 5 (dim 0)

In [ ]:
a_centered_sp = e[0]*f[0]+e[1]*f[1]+e[2]*f[2]+e[3]*f[3]+e[4]*f[4]
a_centered_sp

array([8.])

In [ ]:
a_centered_sp / (len(a[:])-1)
a_centered_sp

array([8.])

##Библиотека pandas ДЗ1

Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [2]:
import pandas as pd
authors = pd.DataFrame({'author_id' : [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']},
                                                                  columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [8]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3], 'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой',
                                                                         'Гроза', 'Таланты и поклонники'], 'price' : [450, 300, 350, 500, 450, 370, 290]},
                    columns = ['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [20]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [10]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [31]:
authors_stat2 = authors_price.drop('author_id', axis = 1)
authors_stat1 = authors_stat2.drop('book_title', axis = 1)
authors_stat = authors_stat1.drop('price', axis = 1)
authors_stat

author_name
0    Тургенев
1    Тургенев
2    Тургенев
3       Чехов
4       Чехов
5  Островский
6  Островский

In [38]:
authors_stat2 = authors_price.groupby('author_name').agg({'price':'min'})
authors_stat2 = authors_stat2.rename(columns = {'price':'min_price'})
authors_stat2

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [39]:
authors_stat1 = authors_price.groupby('author_name').agg({'price':'max'})
authors_stat1 = authors_stat1.rename(columns = {'price':'max_price'})
authors_stat1

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [41]:
authors_stat3 = authors_price.groupby('author_name').agg({'price':'mean'})
authors_stat3 = authors_stat3.rename(columns = {'price':'mean_price'})
authors_stat3

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [43]:
authors_stat = pd.concat([authors_stat2, authors_stat1, authors_stat3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000